// Code generated by protoc-gen-go.
// source: demo.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	demo.proto

It has these top-level messages:
	GuestBookEntry
	ListGuestBookResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GuestBookEntry struct {
	Name    string                      `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Message string                      `protobuf:"bytes,2,opt,name=Message,json=message" json:"Message,omitempty"`
	Time    *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=Time,json=time" json:"Time,omitempty"`
}

func (m *GuestBookEntry) Reset()                    { *m = GuestBookEntry{} }
func (m *GuestBookEntry) String() string            { return proto1.CompactTextString(m) }
func (*GuestBookEntry) ProtoMessage()               {}
func (*GuestBookEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GuestBookEntry) GetTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

type ListGuestBookResponse struct {
	Entries []*GuestBookEntry `protobuf:"bytes,1,rep,name=Entries,json=entries" json:"Entries,omitempty"`
}

func (m *ListGuestBookResponse) Reset()                    { *m = ListGuestBookResponse{} }
func (m *ListGuestBookResponse) String() string            { return proto1.CompactTextString(m) }
func (*ListGuestBookResponse) ProtoMessage()               {}
func (*ListGuestBookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListGuestBookResponse) GetEntries() []*GuestBookEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto1.RegisterType((*GuestBookEntry)(nil), "grpcdemoproto.GuestBookEntry")
	proto1.RegisterType((*ListGuestBookResponse)(nil), "grpcdemoproto.ListGuestBookResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for GuestBookService service

type GuestBookServiceClient interface {
	Create(ctx context.Context, in *GuestBookEntry, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
	List(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ListGuestBookResponse, error)
}

type guestBookServiceClient struct {
	cc *grpc.ClientConn
}

func NewGuestBookServiceClient(cc *grpc.ClientConn) GuestBookServiceClient {
	return &guestBookServiceClient{cc}
}

func (c *guestBookServiceClient) Create(ctx context.Context, in *GuestBookEntry, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/grpcdemoproto.GuestBookService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestBookServiceClient) List(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*ListGuestBookResponse, error) {
	out := new(ListGuestBookResponse)
	err := grpc.Invoke(ctx, "/grpcdemoproto.GuestBookService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GuestBookService service

type GuestBookServiceServer interface {
	Create(context.Context, *GuestBookEntry) (*google_protobuf.Empty, error)
	List(context.Context, *google_protobuf.Empty) (*ListGuestBookResponse, error)
}

func RegisterGuestBookServiceServer(s *grpc.Server, srv GuestBookServiceServer) {
	s.RegisterService(&_GuestBookService_serviceDesc, srv)
}

func _GuestBookService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestBookEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestBookServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcdemoproto.GuestBookService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestBookServiceServer).Create(ctx, req.(*GuestBookEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestBookService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestBookServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcdemoproto.GuestBookService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestBookServiceServer).List(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _GuestBookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcdemoproto.GuestBookService",
	HandlerType: (*GuestBookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _GuestBookService_Create_Handler,
		},
		{
			MethodName: "List",
			Handler:    _GuestBookService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x51, 0xcf, 0x4b, 0xfb, 0x30,
	0x14, 0x5f, 0xbf, 0x2b, 0x2b, 0xdf, 0x0c, 0x45, 0x02, 0x4a, 0x29, 0x08, 0xa5, 0x0c, 0xe9, 0x65,
	0x29, 0x74, 0x07, 0x0f, 0x9e, 0x9c, 0x4c, 0x2f, 0x2a, 0x52, 0x77, 0xf2, 0x96, 0xd6, 0x67, 0x0c,
	0x36, 0x4d, 0x68, 0xd2, 0x49, 0xff, 0x18, 0xff, 0x57, 0x49, 0xeb, 0xa6, 0xf3, 0xe7, 0xa5, 0xcd,
	0x27, 0xef, 0x7d, 0x7e, 0xe4, 0x3d, 0x84, 0xee, 0x41, 0x48, 0xa2, 0x6a, 0x69, 0x24, 0xde, 0x61,
	0xb5, 0x2a, 0x2c, 0xee, 0x60, 0x30, 0x63, 0xdc, 0x3c, 0x36, 0x39, 0x29, 0xa4, 0x48, 0x98, 0x2c,
	0x69, 0xc5, 0x92, 0xae, 0x90, 0x37, 0x0f, 0x89, 0x32, 0xad, 0x02, 0x9d, 0x80, 0x50, 0xa6, 0xed,
	0xbf, 0xbd, 0x46, 0x70, 0xf2, 0x37, 0xc9, 0x70, 0x01, 0xda, 0x50, 0xa1, 0xde, 0x4f, 0x3d, 0x39,
	0xaa, 0xd0, 0xee, 0x45, 0x03, 0xda, 0xcc, 0xa5, 0x7c, 0x5a, 0x54, 0xa6, 0x6e, 0x31, 0x46, 0xee,
	0x35, 0x15, 0xe0, 0x3b, 0xa1, 0x13, 0xff, 0xcf, 0xdc, 0x8a, 0x0a, 0xc0, 0x3e, 0xf2, 0xae, 0x40,
	0x6b, 0xca, 0xc0, 0xff, 0xd7, 0x5d, 0x7b, 0xa2, 0x87, 0x98, 0x20, 0x77, 0xc9, 0x05, 0xf8, 0xc3,
	0xd0, 0x89, 0xc7, 0x69, 0x40, 0x98, 0x94, 0xac, 0x04, 0xb2, 0x0e, 0x40, 0x96, 0x6b, 0xbf, 0xcc,
	0xb5, 0xd6, 0xd1, 0x0d, 0xda, 0xbf, 0xe4, 0xda, 0x6c, 0x3c, 0x33, 0xd0, 0x4a, 0x56, 0x1a, 0xf0,
	0x31, 0xf2, 0xac, 0x3f, 0x07, 0xed, 0x3b, 0xe1, 0x30, 0x1e, 0xa7, 0x87, 0x64, 0x6b, 0x36, 0x64,
	0x3b, 0x66, 0xe6, 0x41, 0xdf, 0x9d, 0xbe, 0x38, 0x68, 0x6f, 0x53, 0xbb, 0x85, 0x7a, 0xc5, 0x0b,
	0xc0, 0xa7, 0x68, 0x74, 0x56, 0x03, 0x35, 0x80, 0x7f, 0x97, 0x09, 0x0e, 0xbe, 0x24, 0x5e, 0xd8,
	0xd1, 0x46, 0x03, 0x7c, 0x8e, 0x5c, 0x9b, 0x14, 0xff, 0xd0, 0x11, 0x4c, 0x3e, 0x09, 0x7f, 0xfb,
	0xac, 0x68, 0x30, 0x3f, 0xba, 0x9b, 0x7c, 0x58, 0xd0, 0x33, 0xd0, 0x15, 0x4c, 0x4b, 0x9a, 0x27,
	0x96, 0x3d, 0xb5, 0xf4, 0xb7, 0x6d, 0x8d, 0xba, 0xdf, 0xec, 0x35, 0x00, 0x00, 0xff, 0xff, 0x4c,
	0x7d, 0x03, 0x85, 0x1f, 0x02, 0x00, 0x00,
}
